/** Turn a conversation (user + assistant turns) into clean Markdown. */
export function conversationToMarkdown(messages) {
  const lines = ["# ZSR Research Navigator — Research Plan", ""];

  for (const m of messages) {
    if (m.role === "user") {
      lines.push(`## You asked`, "", m.content, "");
      continue;
    }
    const r = m.reply || {};
    if (r.message) lines.push(r.message, "");

    if (r.starting_points?.length) {
      lines.push("### Recommended starting points", "");
      for (const sp of r.starting_points) {
        lines.push(`- [${sp.resource_name}](${sp.url}) — ${sp.why}`);
      }
      lines.push("");
    }
    if (r.search_terms?.length) {
      lines.push("### Search terms to try", "");
      for (const t of r.search_terms) lines.push(`- \`${t}\``);
      lines.push("");
    }
    if (r.database_strategy?.length) {
      lines.push("### Where to search in ZSR", "");
      for (const item of r.database_strategy) {
        if (!item.database) continue;
        lines.push(`- ${item.database}`);
        if (item.az_area) lines.push(`  - A-Z area: ${item.az_area}`);
        if (item.why) lines.push(`  - Why: ${item.why}`);
        if (item.search_inside?.length) {
          lines.push(`  - Search inside: ${item.search_inside.join("; ")}`);
        }
        if (item.journals_or_sources?.length) {
          lines.push(`  - Journals/source leads: ${item.journals_or_sources.join("; ")}`);
        }
      }
      lines.push("");
    }
    if (r.source_evaluation?.length) {
      lines.push("### Evaluating your sources", "");
      for (const t of r.source_evaluation) lines.push(`- ${t}`);
      lines.push("");
    }
    if (r.academic_integrity_note) {
      lines.push("### Responsible AI & academic integrity", "", r.academic_integrity_note, "");
    }
    if (r.limitations) lines.push("### Limitations", "", r.limitations, "");

    if (m.liveResults?.length) {
      lines.push("### Real results in ZSR's catalog", "");
      for (const item of m.liveResults) {
        lines.push(`- [${item.title}](${item.url})`);
        const meta = [item.type, item.author, item.date].filter(Boolean).join(" · ");
        if (meta) lines.push(`  - ${meta}`);
        if (item.description) lines.push(`  - ${item.description}`);
      }
      lines.push("");
    }
  }

  lines.push(
    "---",
    "",
    "_Generated by the ZSR Research Navigator (AI). Responses are AI-generated — verify links and consult a librarian. This tool does not search live databases or access paywalled full-text content._"
  );
  return lines.join("\n");
}

/** Trigger a client-side download of text content. */
export function downloadText(filename, text) {
  const blob = new Blob([text], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

export function conversationToPlainText(messages) {
  return conversationToMarkdown(messages)
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, "$1 — $2")
    .replace(/[`*_#]/g, "")
    .replace(/\n{3,}/g, "\n\n");
}

function pdfSafe(text) {
  return String(text || "")
    .normalize("NFKD")
    .replace(/[^\x20-\x7E\n]/g, "")
    .replace(/[()\\]/g, "\\$&");
}

function wrapLine(text, max = 88) {
  const words = String(text || "").split(/\s+/);
  const lines = [];
  let current = "";
  for (const word of words) {
    if (!word) continue;
    const next = current ? `${current} ${word}` : word;
    if (next.length > max && current) {
      lines.push(current);
      current = word;
    } else {
      current = next;
    }
  }
  if (current) lines.push(current);
  return lines.length ? lines : [""];
}

function textToPdfBytes(title, body) {
  const rawLines = [`${title}`, "", ...String(body || "").split("\n")];
  const wrapped = rawLines.flatMap((line) => wrapLine(line, 92));
  const pages = [];
  for (let i = 0; i < wrapped.length; i += 42) {
    pages.push(wrapped.slice(i, i + 42));
  }

  const objects = [];
  const add = (content) => {
    objects.push(content);
    return objects.length;
  };

  const catalogId = add("<< /Type /Catalog /Pages 2 0 R >>");
  const pagesId = add("");
  const fontId = add("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>");
  const pageIds = [];

  for (const pageLines of pages) {
    const stream = [
      "BT",
      "/F1 10 Tf",
      "50 760 Td",
      "14 TL",
      ...pageLines.map((line) => `(${pdfSafe(line)}) Tj T*`),
      "ET",
    ].join("\n");
    const streamId = add(`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`);
    const pageId = add(`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 ${fontId} 0 R >> >> /Contents ${streamId} 0 R >>`);
    pageIds.push(pageId);
  }

  objects[pagesId - 1] = `<< /Type /Pages /Kids [${pageIds.map((id) => `${id} 0 R`).join(" ")}] /Count ${pageIds.length} >>`;
  objects[catalogId - 1] = "<< /Type /Catalog /Pages 2 0 R >>";

  let pdf = "%PDF-1.4\n";
  const offsets = [0];
  objects.forEach((content, index) => {
    offsets.push(pdf.length);
    pdf += `${index + 1} 0 obj\n${content}\nendobj\n`;
  });
  const xref = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (let i = 1; i < offsets.length; i += 1) {
    pdf += `${String(offsets[i]).padStart(10, "0")} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;

  return new Uint8Array([...pdf].map((char) => char.charCodeAt(0)));
}

export function downloadPdf(filename, title, text) {
  const bytes = textToPdfBytes(title, text);
  const blob = new Blob([bytes], { type: "application/pdf" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
